trialtask/trialapp/urls.py
from django.urls import path
from .views import *

app_name = "trialapp"

urlpatterns = [
    path("", home, name="home"),
    path("scrape/", scrape_request, name="scrape"),
    path("download/", download_file, name="download-file"),
    path("getfile/", get_file, name="get_file"),
]

trialtask/trialtask/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path("", include("trialapp.urls")),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

trialtask/trialapp/models.py
from django.db import models

# Create your models here.

trialtask/trialapp/views.py
from django.shortcuts import render, redirect
from .async_scrapper import scrapper_main, settings
from django.http import HttpResponse, Http404
import os

# Create your views here.

CATEGORIES = ['data-science', 'business', 'computer-science', 'personal-development', 'social-sciences',
              'arts-and-humanities']


def home(request):
    return render(request, "trialapp/home.html", context={"categories": CATEGORIES})


def scrape_request(request):
    if request.method == "POST":
        if request.POST:
            category = request.POST.get("cats")
            print(category)
            scrapper_main(category)
    return redirect("trialapp:download-file")


def download_file(request):
    files_list = os.listdir(f"{settings.MEDIA_ROOT}/files/")
    return render(request, "trialapp/download.html", context={"files": files_list})


def get_file(request):
    if request.method == "POST":
        print(request.POST)
        filename = request.POST.get("filename")
        filepath = fr"{settings.MEDIA_ROOT}\files\{filename}"
        print(filepath)
        if os.path.exists(filepath):
            with open(filepath, 'rb') as fh:
                response = HttpResponse(fh.read(), content_type="application/vnd.ms-excel")
                response['Content-Disposition'] = 'inline; filename=' + os.path.basename(filepath)
                return response
    raise Http404

trialtask/trialapp/templates/trialapp/base.html
<!DOCTYPE html>
<html>
<body>
<br>
<h3><a href="{% url 'trialapp:home' %}">Home</a></h3>
<br>
<h3><a href="{% url 'trialapp:download-file' %}">View or Download Existing files</a></h3>
{% block main %}

{% endblock%}

</body>
</html>

trialtask/trialapp/templates/trialapp/download.html
{% extends "trialapp/base.html" %}
{%block main%}

<h1>Download Scrapped File</h1>
Availables files list:
{% if files %}
<ol>
    {% for file in files %}
    <li>{{file | title}}</li>
    {% endfor %}
</ol>
{% else %}
<p>No scrapped files are available. Please go 'home' and scrape data from given categories. </p>
{% endif %}
<p>Choose one of the files to download</p>

<form action="{% url 'trialapp:get_file' %}" method="POST">
    {% csrf_token %}
    <select name="filename" id="file">
        {% for file in files %}
        <option value="{{file}}" name="{{file}}">{{file | title}}</option>
        {% endfor %}
    </select>
    <br><br>
    <input type="submit" value="Submit">
</form>

<p>Click the "Submit" button download selected file.</p>

{%endblock%}

trialtask/trialapp/templates/trialapp/home.html
{% extends "trialapp/base.html" %}
{%block main%}
<h1>Data Scrapper from Coursera</h1>

<p><h3>Please select one of categories form a drop-down list.</h3></p>

<form action="{% url 'trialapp:scrape' %}" method="POST">
    {% csrf_token %}
    <label for="cats"><h4>Choose a category to scrape data from</h4></label>
    <select name="cats" id="cats">
        {% for cat in categories %}
        <option value="{{cat}}" name="{{cat}}">{{cat | title}}</option>
        {% endfor %}
    </select>
    <br><br>
    <input type="submit" value="Submit">
</form>

<p>Click the "Submit" button to scrape data.
    Please wait until you will be redirected to the corresponding page.</p>
{%endblock%}